### ISSUE TITLE
benchmarks fail to build with ghc-9.10.1

### ISSUE THREAD

**Issue by juhp** [sergv/bencoding#6]
For stackage nightly ghc-9.10.1:

```
       Building benchmark 'bench-comparison' for bencoding-0.4.5.5...                                                               
       [1 of 1] Compiling Main
       /home/curators/work/unpack-dir/unpacked/bencoding-0.4.5.5-0abaab18199db37819d55369538778fe7e99c5c1c78c0f4a658a71d0b565b9bb/be
nch/Main.hs:58:23: error: [GHC-87543]                                                                                               
           Ambiguous occurrence ‘List’.                           
           It could refer to                                      
              either ‘L.List’,
                     imported from ‘Data.List’ at bench/Main.hs:22:1-21                                                             
                     (and originally defined in ‘GHC.Types’),                                                                       
                  or ‘Main.List’, defined at bench/Main.hs:58:1.  
          |                                                                                                                         
       58 | data List a = Cons a (List a) | Nil                                                                                     
          |                       ^^^^                                                                                              
                                                                  
       /home/curators/work/unpack-dir/unpacked/bencoding-0.4.5.5-0abaab18199db37819d55369538778fe7e99c5c1c78c0f4a658a71d0b565b9bb/be
nch/Main.hs:61:36: error: [GHC-87543]                                                                                               
           Ambiguous occurrence ‘List’.                      
           It could refer to                                                                                                        
              either ‘L.List’,                                                                                                      
                     imported from ‘Data.List’ at bench/Main.hs:22:1-21                                                             
                     (and originally defined in ‘GHC.Types’),
                  or ‘Main.List’, defined at bench/Main.hs:58:1.  
          |                                                                                                                         
       61 | instance C.BEncode a => C.BEncode (List a)            
          |                                    ^^^^                                                                                 
                            
       /home/curators/work/unpack-dir/unpacked/bencoding-0.4.5.5-0abaab18199db37819d55369538778fe7e99c5c1c78c0f4a658a71d0b565b9bb/be
nch/Main.hs:63:30: error: [GHC-87543]                                                                                               
           Ambiguous occurrence ‘List’.                      
           It could refer to                                      
              either ‘L.List’,
                     imported from ‘Data.List’ at bench/Main.hs:22:1-21
                     (and originally defined in ‘GHC.Types’),
                  or ‘Main.List’, defined at bench/Main.hs:58:1.
          |
       63 | instance NFData a => NFData (List a) where
          |                              ^^^^
        
       /home/curators/work/unpack-dir/unpacked/bencoding-0.4.5.5-0abaab18199db37819d55369538778fe7e99c5c1c78c0f4a658a71d0b565b9bb/be
nch/Main.hs:67:27: error: [GHC-87543]
           Ambiguous occurrence ‘List’.
:
:
```

**Comment by sergv** [comment]
Thanks for the report, fixed in `0.4.5.6`.
