### ISSUE TITLE
fails to build with ghc-9.6 stackage nightly

### ISSUE THREAD

**Issue by juhp** [sergv/bencoding#4]
```
      Building library for bencoding-0.4.5.4..                                                                                     
       [4 of 4] Compiling Data.BEncode                                                                                              
                                 
       /var/stackage/work/unpack-dir/unpacked/bencoding-0.4.5.4-f895d5fb0ac15a532aa4e7301fd61d0c9d401f412b41b1f3f064f81040a72b97/src
/Data/BEncode.hs:671:35: error: [GHC-39999]
           • No instance for ‘MonadPlus (Either String)’                                                                            
               arising from the 'deriving' clause of a data type declaration                                                        
             Possible fix:       
               use a standalone 'deriving instance' declaration,                                                                    
                 so you can specify the instance context yourself                                                                   
           • When deriving the instance for (Alternative Get)                                                                       
           |                                                                                                                        
       671 |   deriving (Functor, Applicative, Alternative)                                                                         
           |                                   ^^^^^^^^^^^
```

**Comment by sergv** [comment]
Fix released as `0.4.5.5`.
